version: "3"
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./html:/app/test1
      - ./nginx/sitio2.conf:/etc/nginx/conf.d/sitio2.conf
  php:
    build: php
    volumes:
      - ./html:/app/test1    
      - ./php/www.conf:/etc/php/8.2/fpm/pool.d/www.conf